--- 
abstract: ~
author: ~
build_requires: 
  Test::Declare: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.680
license: unknown
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Perlbal-Plugin-StickySessions
no_index: 
  directory: 
    - inc
    - t
#requires: 
version: 0.01
